import type { GetStaticProps } from "next";
import Link from "next/link";
import Head from "next/head";
import { getCSS } from "../../lib/data";
import styles from "../../styles/Home.module.css";
import React from "react";

const HTML = ({ posts }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>CSS</h1>
        <div className={styles.grid}>
          {posts.map(
            (
              item: { permalink: string; title: string; subtitle: string },
              index: React.Key
            ) => {
              return (
                <Link
                  href="/css/[slug]"
                  as={`/css/${item.permalink}`}
                  key={index}
                >
                  <a className={styles.card}>
                    <h2>{item.title} &rarr;</h2>
                    <p>{item.subtitle}</p>
                  </a>
                </Link>
              );
            }
          )}
        </div>
      </main>
    </div>
  );
};

export default HTML;

export const getStaticProps: GetStaticProps = async (ctx) => {
  const allPost = getCSS();
  return {
    props: {
      posts: allPost.map(({ data, content, permalink }) => ({
        ...data,
        content,
        permalink,
      })),
    },
  };
};
